---
- hosts: aaulan_webserver
  gather_facts: False
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Setup webserver
  hosts: aaulan_webserver
  become: yes

  vars:
    certbot_admin_email: aaulan@aaulan.dk
    certbot_create_if_missing: true
    certbot_auto_renew_options: "--quiet --no-self-upgrade --pre-hook 'systemctl stop nginx' --post-hook 'systemctl start nginx'"
    certbot_create_standalone_stop_services: []
    dh_params: "/opt/dhparams.pem"

    certbot_certs:
      - domains:
        - home.mikkel.cc

    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "home.mikkel.cc"
        root: "/var/www/aaulan.dk"
        index: "index.htm index.html"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "aaulan.dk.conf"
        extra_parameters: |
          ssl_certificate        /etc/letsencrypt/live/aaulan.dk/fullchain.pem;
          ssl_certificate_key    /etc/letsencrypt/live/aaulan.dk/privkey.pem;
          ssl_dhparam            {{ dh_params }}
          ssl_protocols          TLSv1.1 TLSv1.2;
          ssl_ciphers "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS";
          ssl_prefer_server_ciphers on;
          ssl_session_cache shared:le_nginx_SSL:1m;
          ssl_session_timeout 1440m;

      - listen: "80 default_server"
        server_name: "_"
        return: "301 https://$host$request_uri"
        filename: "ssl_redirect.conf"

    nginx_remove_default_vhost: true
    nginx_ppa_use: true
    nginx_ppa_version: stable
  
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    
    - name: Install dependencies (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

    - name: Install rng-tools
      apt:
        name: rng-tools
        state: present
      
    - name: Speed up entropy
      command: rngd -r /dev/urandom

    - name: Generate DH parameters (This takes ages > 15min)
      openssl_dhparam:
        path: '{{ dh_params }}'
        size: 4096

  roles:
    - geerlingguy.certbot
    - geerlingguy.nginx

  tasks:
    - name: Flush handlers in case any configs have changed.
      meta: flush_handlers

    - name: Make directory for website
      file:
        path: "/var/www/aaulan.dk"
        state: directory

    - include_role:
        name: get-website

    - include_role:
        name: firewall

    - include_role:
        name: unattended-upgrades
