---
- name: Setup webserver
  hosts: webserver
  become: yes
  tasks:
    - name: Install docker
      apt:
        name: docker
        state: latest

    - include_role:
        name: webserver

    - include_role:
        name: firewall

    - include_role:
        name: unattended-upgrades
