---
- name: Bootstrap python 2
  hosts: aaulan_webserver
  become: true
  gather_facts: false

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Install nginx
  hosts: aaulan_webserver
  become: true

  vars:
    server_webroot: '/var/www/aaulan.dk'

    acme_install_cert: true
    acme_cert_dir: '/var/www/certs'
    acme_keyfile_name: 'key.pem'
    acme_fullchain_name: 'chain.pem'
    acme_domains:
      - 'home.mikkel.cc'

  pre_tasks:
    - name: Remove apache
      apt: 
        name: apache2
        state: absent

    - name: Install pip
      apt:
        name: python-pip
        state: present
    
    - name: Ensure python OpenSSL dependencies are installed.
      pip:
        name: pyOpenSSL
        state: present

    - name: Ensure certificate location exists
      file:
        dest: '{{ acme_cert_dir }}'
        state: directory

    - name: Install rng-tools
      apt:
        name: rng-tools
        state: present
      
    - name: Speed up entropy
      command: rngd -r /dev/urandom

    - name: Generate DH parameters (This takes ages > 15min)
      openssl_dhparam:
        path: '{{ acme_cert_dir }}/dhparams.pem'
        size: 4096

    - name: Generate an OpenSSL private key.
      openssl_privatekey:
        path: '{{ acme_cert_dir }}/{{ acme_keyfile_name }}'

    - name: Generate an OpenSSL CSR.
      openssl_csr:
        path: ~/temp.csr
        privatekey_path: '{{ acme_cert_dir }}/{{ acme_keyfile_name }}'
        common_name: "temp"

    - name: Generate a Self Signed OpenSSL certificate.
      openssl_certificate:
        path: '{{ acme_cert_dir }}/{{ acme_fullchain_name }}'
        privatekey_path: '{{ acme_cert_dir }}/{{ acme_keyfile_name }}'
        csr_path: ~/temp.csr
        provider: selfsigned

  roles:
    - nginxinc.nginx

  post_tasks:
    - name: Set up nginx configuration for site
      template:
        src: templates/website.conf.j2
        dest: /etc/nginx/conf.d/aaulan.dk.conf
    
    - name: Remove default nginx configuration
      file:
        dest: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Reload nginx
      service: 
        name: nginx
        state: reloaded

- name: Install acme.sh and aquire certs
  hosts: aaulan_webserver
  become: true

  vars:
    acme_install_cert: true
    acme_issue_mode: 'nginx'

    acme_webroot_dir_owner: 'nginx'
    acme_cert_dir_group: 'nginx'

    acme_reload_service_command: 'systemctl reload nginx'
    acme_issue_command: "{{ acme_script }} --issue --test --pre-hook '{{ acme_pre_hook }}' --post-hook '{{ acme_post_hook }}' -d {{ acme_domains | join(' -d ') }}"

    acme_sudo_reload_httpd: false
    acme_sudo_reload_haproxy: false

    acme_user: 'root'

    acme_cert_dir: '/var/www/certs'
    acme_keyfile_name: 'key.pem'
    acme_fullchain_name: 'chain.pem'
    acme_domains:
      - 'home.mikkel.cc'

  roles:
    - acme.sh
  