---
- name: Setup webserver
  hosts: webserver
  become: yes

  vars:
    certbot_admin_email: aaulan@aaulan.dk
    certbot_create_if_missing: true
    certbot_auto_renew_options: "--quiet --no-self-upgrade --pre-hook 'systemctl stop nginx' --post-hook 'systemctl start nginx'"
    certbot_create_standalone_stop_services: []

    certbot_certs:
      - domains:
        - aaulan.dk

    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "aaulan.dk"
        root: "/var/www/aaulan.dk"
        index: "index.htm index.html"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "aaulan.dk.conf"
        extra_parameters: |
          ssl_certificate        /etc/letsencrypt/live/aaulan.dk/fullchain.pem;
          ssl_certificate_key    /etc/letsencrypt/live/aaulan.dk/privkey.pem;
          ssl_protocols          TLSv1.1 TLSv1.2;
          ssl_ciphers            HIGH:!aNULL:!MD5;

      - listen: "80 default_server"
        server_name: "_"
        return: "301 https://$host$request_uri"
        filename: "ssl_redirect.conf"

    nginx_remove_default_vhost: true
    nginx_ppa_use: true
    nginx_ppa_version: stable
  
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    
    - name: Install dependencies (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.certbot
    - geerlingguy.nginx

  tasks:
    - name: Flush handlers in case any configs have changed.
      meta: flush_handlers

    - name: Make directory for website
      file:
        path: "/var/www/aaulan.dk"
        state: directory

    - name: Put placeholder website in placeholder
      copy:
        dest: "/var/www/aaulan.dk/index.html"
        content: |
          <html><head><title>It works!</title></head>
          <body>
           <h2> Server successfully deployed.</h2>
          </body>

    - include_role:
        name: firewall

    - include_role:
        name: unattended-upgrades
