---
- name: Bootstrap python 2
  hosts: aaulan_webserver
  become: true
  gather_facts: false

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- name: Install acme.sh and aquire certs
  hosts: aaulan_webserver
  become: true

  vars_files:
    - vars/gdns_credentials.yml

  vars:
    acme_sh_account_email: "crew@aaulan.dk"
    acme_sh_copy_certs_to_path: "/var/www/certs"

    acme_sh_default_staging: False
    acme_sh_default_force_issue: True
    acme_sh_default_dns_provider: "dns_gdnsdk"
    acme_sh_default_dns_sleep: 360

    acme_sh_domains:
      - domains: ["aaulan.dk", "*.aaulan.dk"]
        debug: False

  roles:
    - { role: "nickjj.acme_sh", tags: ["acme_sh"] }


- name: Install nginx
  hosts: aaulan_webserver
  become: true

  vars:
    domains: 
      - 'aaulan.dk'
      - '*.aaulan.dk'

    server_webroot: '/var/www/{{ domains[0] }}'

    acme_cert_dir: '/var/www/certs'
    acme_keyfile_name: '{{ domains[0] }}.key'
    acme_fullchain_name: '{{ domains[0] }}.pem'

  pre_tasks:
    - name: Remove apache
      apt: 
        name: apache2
        state: absent

    - name: Install pip
      apt:
        name: python-pip
        state: present
    
    - name: Ensure python OpenSSL dependencies are installed.
      pip:
        name: pyOpenSSL
        state: present

    - name: Ensure certificate location exists
      file:
        dest: '{{ acme_cert_dir }}'
        state: directory

    - name: Install rng-tools
      apt:
        name: rng-tools
        state: present
      
    - name: Speed up entropy
      command: rngd -r /dev/urandom

    - name: Generate DH parameters
      openssl_dhparam:
        path: '{{ acme_cert_dir }}/dhparams.pem'
        size: 2048

  roles:
    - nginxinc.nginx

  post_tasks:
    - name: Set up nginx configuration for site
      template:
        src: templates/website.conf.j2
        dest: /etc/nginx/conf.d/aaulan.dk.conf
    
    - name: Remove default nginx configuration
      file:
        dest: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Reload nginx
      service: 
        name: nginx
        state: reloaded

- name: Get website and finish up
  hosts: aaulan_webserver
  become: true

  tasks:
  - name: Make directory for website
    file:
      path: "/var/www/aaulan.dk"
      state: directory

  - include_role:
      name: get-website

  - include_role:
     name: firewall

  - include_role:
     name: unattended-upgrades