---
# heavily inspired by https://gist.github.com/lachesis/943769f3fac740d5848352752ac08741
- name: Create ACME.sh user
  user:
      name: '{{ acme_user }}'
      home: '/home/{{ acme_user }}' 
      state: present
  when: acme_user != 'root'

- name: "Tighten permissions on ACME homedir"
  file:
    path: '/home/{{ acme_user }}'
    mode: '700'
  when: acme_user != 'root'

- name: Make sure socat is present (for standalone mode)
  yum:
     name: socat
     state: present
  when:
    - ansible_os_family == "RedHat"

- name: Make sure socat is present (for standalone mode)
  apt:
     name: socat
     state: present
  when:
    - ansible_os_family == "Debian"

- name: Make sure curl is present
  yum:
     name: curl
     state: present
  when:
    - ansible_os_family == "RedHat"

- name: Make sure curl is present
  apt:
     name: curl
     state: present
  when:
    - ansible_os_family == "Debian"

- name: Install acme.sh
  command: 'curl https://get.acme.sh | sh'

- import_tasks: get_cert_apache.yml
  when: 
    - acme_install_cert
    - acme_issue_mode == 'apache'

- import_tasks: get_cert_nginx.yml
  when:
    - acme_install_cert
    - acme_issue_mode == 'nginx'

- import_tasks: get_cert_webroot.yml
  when:
    - acme_install_cert
    - acme_issue_mode == 'webroot'

- import_tasks: get_cert_standalone.yml
  when:
    - acme_install_cert
    - acme_issue_mode == 'standalone'