- name: Install ufw
  apt:
    name: ufw
    state: latest

- name: Firewall allow HTTP
  ufw:
    rule: allow
    port: http

- name: Firewall allow HTTPS
  ufw:
    rule: allow
    port: https

- name: Firewall allow SSH
  ufw:
    rule: allow
    port: ssh

- name: Enable ufw
  ufw:
    direction: incoming
    policy: deny
    state: enabled
