---
galaxy_info:
  author: Duckle29
  description: This role downloads and sets up acme.sh, and issues a cert with it
  license: BSD
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
    - bionic
    
dependencies: []
